- name: Installing dependencies
  shell: composer require romeoz/rock-template:0.11.* romeoz/rock-date:0.10.* chdir={{ root_dir }}
  tags: demo

- name: chown project
  shell: chown {{ username }}:{{ username }} {{ root_dir }} -Rf
  tags: demo