- name: Download and uncompress Couchbase Server
  shell: chdir="/tmp" wget http://packages.couchbase.com/releases/3.0.1/couchbase-server-community_3.0.1-ubuntu12.04_amd64.deb; sudo dpkg -i couchbase-server-community_3.0.1-ubuntu12.04_amd64.deb
#For x86
#  shell: chdir="/tmp" wget http://packages.couchbase.com/releases/2.2.0/couchbase-server-community_2.2.0_x86.deb; sudo dpkg -i couchbase-server-community_2.2.0_x86.deb
  tags: couchbase

- name: Add couchbase.list to sources.list  
  shell: sudo wget -O/etc/apt/sources.list.d/couchbase.list http://packages.couchbase.com/ubuntu/couchbase-ubuntu1204.list; sudo wget -O- http://packages.couchbase.com/ubuntu/couchbase.key | sudo apt-key add -  
  tags: couchbase

- name: update apt cache
  apt: update_cache=yes
  tags: couchbase

- name: install C Client Library
  apt: pkg={{ item }} state=latest
  with_items:
    - libcouchbase2-libevent
    - libcouchbase-dev
  tags: couchbase

- name: autoconf install
  apt: pkg={{ item }} state=latest
  with_items:
    - autoconf

- name: Download and uncompress PECL
  shell: "cd /tmp && wget http://pecl.php.net/get/couchbase-1.2.2.tgz && tar zxvf couchbase-1.2.2.tgz"
  tags: couchbase

- name: Install PECL
  sudo: yes
  shell: "cd /tmp/couchbase-1.2.2 && phpize && ./configure && make install && echo 'extension = couchbase.so' >> /etc/php5/fpm/conf.d/couchbase.ini && echo 'extension = couchbase.so' >> /etc/php5/cli/conf.d/couchbase.ini"
  tags: couchbase

- name: Create test bucket
  sudo: yes
  shell: "/opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=default --bucket-type=memcached --bucket-ramsize=64 --enable-flush=1 -u demo -p demo"
  tags: couchbase
#  shell: sudo pecl install couchbase